# Generated by Django 5.2.5 on 2026-07-13 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreport',
            name='time_spent',
            field=models.IntegerField(default=0),
        ),
    ]
