# Generated by Django 5.2.5 on 2026-07-13 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_dailyreport_time_spent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreport',
            name='task_list',
            field=models.JSONField(default=list),
        ),
    ]
