# Generated by Django 5.2.5 on 2026-07-13 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_dailyreport_task_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreport',
            name='work_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
