# Generated by Django 5.2.5 on 2026-07-15 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_dailyreport_work_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreport',
            name='sub_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
