# Generated by Django 5.2.5 on 2026-07-29 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_taskcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='task_list',
            field=models.JSONField(default=list),
        ),
    ]
